#!/bin/bash

# RoI Align训练示例脚本
# 展示如何使用新添加的区域特征提取功能

echo "=========================================="
echo "SPRC with RoI Align Training Script"
echo "=========================================="
echo ""

# 设置环境
cd /home/caoyu/mnt/zhaoai/SPRC/src

# 方案1: 不使用区域损失（默认训练）
echo "方案1: 标准训练（不使用区域损失）"
echo "------------------------------------------"
echo "命令:"
echo "python blip_fine_tune_2.py \\"
echo "    --dataset CIRR \\"
echo "    --blip-model-name blip2_cir_align_prompt \\"
echo "    --backbone pretrain \\"
echo "    --num-epochs 50 \\"
echo "    --batch-size 128 \\"
echo "    --learning-rate 2e-6 \\"
echo "    --loss-align 0.4 \\"
echo "    --loss-rtc 0.4 \\"
echo "    --validation-frequency 1 \\"
echo "    --save-training \\"
echo "    --save-best"
echo ""
echo "这是默认的训练方式，不使用RoI Align区域损失"
echo ""

# 方案2: 使用区域损失（需要bounding box数据）
echo "方案2: 启用RoI Align区域损失"
echo "------------------------------------------"
echo "命令:"
echo "python blip_fine_tune_2.py \\"
echo "    --dataset CIRR \\"
echo "    --blip-model-name blip2_cir_align_prompt \\"
echo "    --backbone pretrain \\"
echo "    --num-epochs 50 \\"
echo "    --batch-size 128 \\"
echo "    --learning-rate 2e-6 \\"
echo "    --loss-align 0.4 \\"
echo "    --loss-rtc 0.4 \\"
echo "    --use-region-loss \\"
echo "    --loss-region 0.5 \\"
echo "    --validation-frequency 1 \\"
echo "    --save-training \\"
echo "    --save-best"
echo ""
echo "注意: 需要先准备bounding box数据并修改数据加载器"
echo ""

# 方案3: 两阶段训练（推荐）
echo "方案3: 两阶段训练（推荐）"
echo "------------------------------------------"
echo "第一阶段: 全局特征训练 (30 epochs)"
echo "python blip_fine_tune_2.py \\"
echo "    --dataset CIRR \\"
echo "    --blip-model-name blip2_cir_align_prompt \\"
echo "    --backbone pretrain \\"
echo "    --num-epochs 30 \\"
echo "    --batch-size 128 \\"
echo "    --learning-rate 2e-6 \\"
echo "    --loss-align 0.4 \\"
echo "    --loss-rtc 0.4 \\"
echo "    --save-training \\"
echo "    --save-best"
echo ""
echo "第二阶段: 启用区域损失微调 (20 epochs)"
echo "python blip_fine_tune_2.py \\"
echo "    --dataset CIRR \\"
echo "    --blip-model-name blip2_cir_align_prompt \\"
echo "    --backbone pretrain \\"
echo "    --num-epochs 20 \\"
echo "    --batch-size 128 \\"
echo "    --learning-rate 5e-7 \\"
echo "    --loss-align 0.4 \\"
echo "    --loss-rtc 0.4 \\"
echo "    --use-region-loss \\"
echo "    --loss-region 0.5 \\"
echo "    --save-training \\"
echo "    --save-best"
echo ""
echo "这种方式先学习全局特征，再微调局部特征，效果更好"
echo ""

# 参数说明
echo "=========================================="
echo "参数说明"
echo "=========================================="
echo ""
echo "必需参数:"
echo "  --dataset              数据集名称 (CIRR 或 fashionIQ)"
echo "  --blip-model-name      模型名称 (blip2_cir_align_prompt)"
echo "  --backbone             骨干网络 (pretrain 或 pretrain_vitL)"
echo ""
echo "训练参数:"
echo "  --num-epochs           训练轮数 (默认: 300)"
echo "  --batch-size           批次大小 (默认: 512)"
echo "  --learning-rate        学习率 (默认: 2e-6)"
echo "  --num-workers          数据加载线程数 (默认: 2)"
echo ""
echo "损失权重:"
echo "  --loss-align           对齐损失权重 (默认: 0.4)"
echo "  --loss-rtc             相对对比损失权重 (默认: 0.4)"
echo "  --loss-itm             图文匹配损失权重 (默认: 1.0)"
echo "  --loss-region          区域损失权重 (默认: 0.5)"
echo ""
echo "RoI Align相关:"
echo "  --use-region-loss      启用区域损失 (flag)"
echo "  --loss-region          区域损失权重 (默认: 0.5)"
echo ""
echo "其他:"
echo "  --save-training        保存训练模型 (flag)"
echo "  --save-best            只保存最佳模型 (flag)"
echo "  --validation-frequency 验证频率 (默认: 1 epoch)"
echo "  --transform            图像预处理 (targetpad/squarepad)"
echo "  --target-ratio         TargetPad比例 (默认: 1.25)"
echo ""

# 使用建议
echo "=========================================="
echo "使用建议"
echo "=========================================="
echo ""
echo "1. 首次训练:"
echo "   使用方案1，不启用区域损失，验证基础功能"
echo ""
echo "2. 有box数据:"
echo "   使用方案2或方案3，充分利用区域特征"
echo ""
echo "3. 无box数据:"
echo "   可以使用目标检测模型（如YOLO）自动生成boxes"
echo "   或者使用显著性检测方法提取关键区域"
echo ""
echo "4. 调参建议:"
echo "   - loss-region: 0.3-0.7 之间"
echo "   - 如果区域损失过大，降低权重"
echo "   - 如果区域损失过小，增加权重"
echo ""

# 运行测试
echo "=========================================="
echo "运行测试"
echo "=========================================="
echo ""
echo "在训练前，建议先运行测试脚本验证功能:"
echo ""
echo "cd /home/caoyu/mnt/zhaoai/SPRC"
echo "python test_roi_align.py"
echo ""

echo "=========================================="
echo "脚本结束"
echo "=========================================="
